System.config({
  baseURL: "/",
  defaultJSExtensions: true,
  transpiler: "typescript",
  typescriptOptions: {
    "module": "commonjs",
    "emitDecoratorMetadata": true
  },
  paths: {
    "github:*": "jspm_packages/github/*",
    "npm:*": "jspm_packages/npm/*"
  },
  bundles: {
    "dist/boot.js": [
      "app/bootstrap.ts",
      "npm:angular2@2.0.0-alpha.42/router",
      "app/app.component.ts",
      "npm:angular2@2.0.0-alpha.42/angular2",
      "npm:angular2@2.0.0-alpha.42/src/router/router_link",
      "npm:angular2@2.0.0-alpha.42/src/router/instruction",
      "npm:angular2@2.0.0-alpha.42/src/router/router_outlet",
      "npm:angular2@2.0.0-alpha.42/src/router/router",
      "npm:angular2@2.0.0-alpha.42/src/router/hash_location_strategy",
      "npm:angular2@2.0.0-alpha.42/src/router/path_location_strategy",
      "npm:angular2@2.0.0-alpha.42/src/router/route_registry",
      "npm:angular2@2.0.0-alpha.42/src/router/location_strategy",
      "npm:angular2@2.0.0-alpha.42/src/router/route_config_decorator",
      "npm:angular2@2.0.0-alpha.42/src/router/route_definition",
      "npm:angular2@2.0.0-alpha.42/src/router/lifecycle_annotations",
      "npm:angular2@2.0.0-alpha.42/src/router/location",
      "npm:angular2@2.0.0-alpha.42/src/router/route_data",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/exceptions",
      "npm:reflect-metadata@0.1.2",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/lang",
      "npm:zone.js@0.5.8",
      "github:es-shims/es6-shim@0.33.6",
      "npm:angular2@2.0.0-alpha.42/core",
      "npm:angular2@2.0.0-alpha.42/profile",
      "npm:@reactivex/rxjs@5.0.0-alpha.4",
      "npm:angular2@2.0.0-alpha.42/lifecycle_hooks",
      "npm:angular2@2.0.0-alpha.42/bootstrap",
      "npm:angular2@2.0.0-alpha.42/src/core/metadata",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/collection",
      "npm:angular2@2.0.0-alpha.42/src/core/dom/dom_adapter",
      "npm:angular2@2.0.0-alpha.42/src/router/route_recognizer",
      "npm:angular2@2.0.0-alpha.42/src/core/reflection/reflection",
      "npm:angular2@2.0.0-alpha.42/src/router/route_config_impl",
      "npm:angular2@2.0.0-alpha.42/src/router/route_config_nomalizer",
      "npm:angular2@2.0.0-alpha.42/src/router/url_parser",
      "npm:angular2@2.0.0-alpha.42/src/core/util/decorators",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/exception_handler",
      "npm:angular2@2.0.0-alpha.42/src/router/lifecycle_annotations_impl",
      "npm:zone.js@0.5.8/lib/zone",
      "npm:reflect-metadata@0.1.2/Reflect",
      "npm:angular2@2.0.0-alpha.42/src/core/util",
      "github:es-shims/es6-shim@0.33.6/es6-shim",
      "npm:angular2@2.0.0-alpha.42/src/core/di",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes",
      "npm:angular2@2.0.0-alpha.42/src/core/facade",
      "npm:angular2@2.0.0-alpha.42/src/core/bootstrap",
      "npm:angular2@2.0.0-alpha.42/src/core/application",
      "npm:angular2@2.0.0-alpha.42/src/core/linker",
      "npm:angular2@2.0.0-alpha.42/src/core/services",
      "npm:angular2@2.0.0-alpha.42/src/core/lifecycle",
      "npm:angular2@2.0.0-alpha.42/src/core/zone",
      "npm:angular2@2.0.0-alpha.42/src/core/directives",
      "npm:angular2@2.0.0-alpha.42/src/core/render",
      "npm:angular2@2.0.0-alpha.42/src/core/forms",
      "npm:angular2@2.0.0-alpha.42/src/core/debug",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection",
      "npm:angular2@2.0.0-alpha.42/src/router/route_lifecycle_reflector",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/async",
      "npm:angular2@2.0.0-alpha.42/src/core/profile/profile",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/index",
      "npm:angular2@2.0.0-alpha.42/src/core/metadata/di",
      "npm:angular2@2.0.0-alpha.42/src/core/metadata/view",
      "npm:angular2@2.0.0-alpha.42/src/core/metadata/directives",
      "npm:angular2@2.0.0-alpha.42/src/router/path_recognizer",
      "npm:angular2@2.0.0-alpha.42/src/router/async_route_handler",
      "npm:angular2@2.0.0-alpha.42/src/core/reflection/reflector",
      "npm:angular2@2.0.0-alpha.42/src/core/reflection/reflection_capabilities",
      "npm:zone.js@0.5.8/lib/core",
      "github:jspm/nodelibs-process@0.1.2",
      "npm:zone.js@0.5.8/lib/patch/browser",
      "npm:angular2@2.0.0-alpha.42/src/core/di/metadata",
      "npm:angular2@2.0.0-alpha.42/src/core/di/decorators",
      "npm:angular2@2.0.0-alpha.42/src/core/di/forward_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/di/key",
      "npm:angular2@2.0.0-alpha.42/src/core/di/provider",
      "npm:angular2@2.0.0-alpha.42/src/core/di/injector",
      "npm:angular2@2.0.0-alpha.42/src/core/di/opaque_token",
      "npm:angular2@2.0.0-alpha.42/src/core/di/exceptions",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/async_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/date_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/lowercase_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/slice_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/json_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/default_pipes",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/uppercase_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/application_common",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/number_pipe",
      "npm:angular2@2.0.0-alpha.42/src/core/application_tokens",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/directive_resolver",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/application_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/query_list",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/element_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/dynamic_component_loader",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_manager",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/template_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/app_root_url",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_container_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/services/title",
      "npm:angular2@2.0.0-alpha.42/src/core/life_cycle/life_cycle",
      "npm:angular2@2.0.0-alpha.42/src/core/zone/ng_zone",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/url_resolver",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/ng_class",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/ng_style",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/ng_if",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/ng_for",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/ng_switch",
      "npm:angular2@2.0.0-alpha.42/src/core/render/render",
      "npm:angular2@2.0.0-alpha.42/src/core/directives/observable_list_diff",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/model",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/abstract_control_directive",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/control_container",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_control_name",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_model",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_form_control",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_control",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_form",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/default_value_accessor",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_form_model",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_control_group",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/ng_control_status",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/checkbox_value_accessor",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/select_control_value_accessor",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/validators",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/form_builder",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/validators",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/change_detection",
      "npm:angular2@2.0.0-alpha.42/src/core/debug/debug_element_view_listener",
      "npm:angular2@2.0.0-alpha.42/src/core/debug/debug_element",
      "npm:angular2@2.0.0-alpha.42/src/router/sync_route_handler",
      "npm:angular2@2.0.0-alpha.42/src/core/profile/wtf_impl",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Subject",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Rx.KitchenSink",
      "npm:zone.js@0.5.8/lib/patch/functions",
      "github:jspm/nodelibs-process@0.1.2/index",
      "npm:zone.js@0.5.8/lib/patch/promise",
      "npm:zone.js@0.5.8/lib/keys",
      "npm:zone.js@0.5.8/lib/patch/define-property",
      "npm:zone.js@0.5.8/lib/patch/register-element",
      "npm:zone.js@0.5.8/lib/patch/websocket",
      "npm:zone.js@0.5.8/lib/patch/mutation-observer",
      "npm:zone.js@0.5.8/lib/patch/event-target",
      "npm:zone.js@0.5.8/lib/patch/geolocation",
      "npm:zone.js@0.5.8/lib/patch/file-reader",
      "npm:zone.js@0.5.8/lib/patch/property-descriptor",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/intl",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/invalid_pipe_argument_exception",
      "npm:angular2@2.0.0-alpha.42/src/core/di/type_literal",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/runtime_compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/directive_metadata",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/template_compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/source_module",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/template_parser",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/template_normalizer",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/runtime_metadata",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/html_parser",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/command_compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/schema/element_schema_registry",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/style_compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/change_detector_compiler",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/schema/dom_element_schema_registry",
      "npm:angular2@2.0.0-alpha.42/src/core/testability/browser_testability",
      "npm:angular2@2.0.0-alpha.42/src/core/dom/browser_adapter",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/xhr",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/events/event_manager",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/xhr_impl",
      "npm:angular2@2.0.0-alpha.42/src/core/testability/testability",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/anchor_based_app_root_url",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/events/key_events",
      "npm:angular2@2.0.0-alpha.42/src/core/render/api",
      "npm:angular2@2.0.0-alpha.42/src/core/platform_bindings",
      "npm:angular2@2.0.0-alpha.42/src/animate/browser_details",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/shared_styles_host",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/events/hammer_gestures",
      "npm:angular2@2.0.0-alpha.42/src/core/profile/wtf_init",
      "npm:angular2@2.0.0-alpha.42/src/animate/animation_builder",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/proto_view_factory",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_manager_utils",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_pool",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/template_commands",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_listener",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/dom_renderer",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/view_resolver",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/shared",
      "npm:angular2@2.0.0-alpha.42/src/core/forms/directives/control_value_accessor",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/dom_tokens",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/differs/iterable_differs",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/differs/default_keyvalue_differ",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/differs/default_iterable_differ",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/parser/ast",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/differs/keyvalue_differs",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/pipe_resolver",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/exceptions",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/parser/locals",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/interfaces",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/parser/parser",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/parser/lexer",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/constants",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/proto_change_detector",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/binding_record",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/directive_record",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/jit_proto_change_detector",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/dynamic_change_detector",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/change_detector_ref",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/change_detection_util",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Observable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/subjects/SubjectSubscription",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Subscription",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Subscriber",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/combineLatest-static",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/EmptyObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/DeferObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/ForkJoinObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/concat-static",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/FromEventObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/FromEventPatternObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/ArrayObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/FromObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/merge-static",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/IntervalObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/PromiseObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/InfiniteObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/zip-static",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/TimerObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/ErrorObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/RangeObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/bufferCount",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/buffer",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/bufferToggle",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/bufferTime",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/bufferWhen",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/catch",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/combineAll",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/concat",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/combineLatest",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/concatMap",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/concatAll",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/count",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/concatMapTo",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/dematerialize",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/defaultIfEmpty",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/debounceTime",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/debounce",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/delay",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/distinctUntilChanged",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/distinctUntilKeyChanged",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/do",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/elementAt",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/expand",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/filter",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/find",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/findIndex",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/first",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/finally",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/groupBy",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/ignoreElements",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/map",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/last",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/every",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/isEmpty",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mapTo",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/merge",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeMap",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeAll",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/multicast",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/observeOn",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/partition",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeMapTo",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/publish",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/reduce",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/publishReplay",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/repeat",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/publishBehavior",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/retryWhen",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/retry",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/sampleTime",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/sample",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/scan",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/share",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/startWith",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/skip",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/single",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/shareReplay",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/switch",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/subscribeOn",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/switchMapTo",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/switchMap",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/throttle",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/timeInterval",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/takeUntil",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/take",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/timeoutWith",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/toArray",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/timeout",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/windowCount",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/window",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/windowTime",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/windowToggle",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/toPromise",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/withLatestFrom",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/windowWhen",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/zipAll",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/subjects/BehaviorSubject",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/subjects/ReplaySubject",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/ConnectableObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/immediate",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/nextTick",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/Notification",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/ArgumentOutOfRangeError",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/EmptyError",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/VirtualTimeScheduler",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/zip",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/testing/TestScheduler",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/skipUntil",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/materialize",
      "npm:zone.js@0.5.8/lib/utils",
      "npm:process@0.11.2",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/util",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/interfaces",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/selector",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/template_ast",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/directive_lifecycle_reflector",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/template_preparser",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/style_url_resolver",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/html_ast",
      "npm:angular2@2.0.0-alpha.42/src/transform/template_compiler/change_detector_codegen",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/change_definition_factory",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/change_detection_jit_generator",
      "npm:angular2@2.0.0-alpha.42/src/core/compiler/shadow_css",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/events/hammer_common",
      "npm:angular2@2.0.0-alpha.42/src/core/facade/math",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/pipes",
      "npm:angular2@2.0.0-alpha.42/src/core/dom/generic_browser_adapter",
      "npm:angular2@2.0.0-alpha.42/src/core/pipes/pipe_provider",
      "npm:angular2@2.0.0-alpha.42/src/animate/css_animation_builder",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/element_binder",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/element_injector",
      "npm:angular2@2.0.0-alpha.42/render",
      "npm:angular2@2.0.0-alpha.42/src/core/render/dom/util",
      "npm:angular2@2.0.0-alpha.42/src/core/render/view_factory",
      "npm:angular2@2.0.0-alpha.42/src/core/render/view",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/event_binding",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/coalesce",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/proto_record",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/pipe_lifecycle_reflector",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/abstract_change_detector",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/root",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/throwError",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/noop",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/Symbol_observable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/tryOrOnError",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/tryCatch",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/combineLatest-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/errorObject",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/ScalarObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/IteratorObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/isNumeric",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeAll-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/Symbol_iterator",
      "github:jspm/nodelibs-buffer@0.1.0",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/bindCallback",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeMapTo-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/mergeMap-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/extended/find-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/expand-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/Map",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/FastMap",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/not",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/zip-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/groupBy-support",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/OuterSubscriber",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/subscribeToResult",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/isDate",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/observables/SubscribeOnObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/NextTickScheduler",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/ImmediateScheduler",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/testing/SubscriptionLog",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/testing/HotObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/testing/ColdObservable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/operators/observeOn-support",
      "npm:process@0.11.2/browser",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/pipes",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/codegen_facade",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/codegen_logic_util",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/codegen_name_util",
      "npm:angular2@2.0.0-alpha.42/src/animate/css_animation_options",
      "npm:angular2@2.0.0-alpha.42/src/animate/animation",
      "npm:angular2@2.0.0-alpha.42/src/core/linker/event_config",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/InnerSubscriber",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/NextTickAction",
      "npm:angular2@2.0.0-alpha.42/src/core/change_detection/observable_facade",
      "github:jspm/nodelibs-buffer@0.1.0/index",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/FutureAction",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/applyMixins",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/testing/SubscriptionLoggable",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/schedulers/ImmediateAction",
      "npm:buffer@3.5.1",
      "npm:@reactivex/rxjs@5.0.0-alpha.4/dist/cjs/util/Immediate",
      "npm:buffer@3.5.1/index",
      "npm:base64-js@0.0.8",
      "npm:is-array@1.0.1",
      "npm:ieee754@1.1.6",
      "npm:is-array@1.0.1/index",
      "npm:base64-js@0.0.8/lib/b64",
      "npm:ieee754@1.1.6/index"
    ]
  },

  packages: {
    "app": {
      "defaultExtension": "ts"
    }
  },

  meta: {
    "angular2/angular2": {
      "deps": [
        "reflect-metadata",
        "zone.js",
        "es6-shim",
        "@reactivex/rxjs"
      ]
    }
  },

  map: {
    "@reactivex/rxjs": "npm:@reactivex/rxjs@5.0.0-alpha.4",
    "angular2": "npm:angular2@2.0.0-alpha.42",
    "es6-shim": "github:es-shims/es6-shim@0.33.6",
    "reflect-metadata": "npm:reflect-metadata@0.1.2",
    "typescript": "npm:typescript@1.6.2",
    "zone.js": "npm:zone.js@0.5.8",
    "github:jspm/nodelibs-assert@0.1.0": {
      "assert": "npm:assert@1.3.0"
    },
    "github:jspm/nodelibs-buffer@0.1.0": {
      "buffer": "npm:buffer@3.5.1"
    },
    "github:jspm/nodelibs-constants@0.1.0": {
      "constants-browserify": "npm:constants-browserify@0.0.1"
    },
    "github:jspm/nodelibs-crypto@0.1.0": {
      "crypto-browserify": "npm:crypto-browserify@3.10.0"
    },
    "github:jspm/nodelibs-events@0.1.1": {
      "events": "npm:events@1.0.2"
    },
    "github:jspm/nodelibs-path@0.1.0": {
      "path-browserify": "npm:path-browserify@0.0.0"
    },
    "github:jspm/nodelibs-process@0.1.2": {
      "process": "npm:process@0.11.2"
    },
    "github:jspm/nodelibs-stream@0.1.0": {
      "stream-browserify": "npm:stream-browserify@1.0.0"
    },
    "github:jspm/nodelibs-string_decoder@0.1.0": {
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "github:jspm/nodelibs-util@0.1.0": {
      "util": "npm:util@0.10.3"
    },
    "github:jspm/nodelibs-vm@0.1.0": {
      "vm-browserify": "npm:vm-browserify@0.0.4"
    },
    "npm:@reactivex/rxjs@5.0.0-alpha.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:angular2@2.0.0-alpha.42": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "reflect-metadata": "npm:reflect-metadata@0.1.2",
      "rx": "npm:rx@2.5.1",
      "zone.js": "npm:zone.js@0.5.8"
    },
    "npm:asn1.js@2.2.1": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "bn.js": "npm:bn.js@2.2.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0",
      "vm": "github:jspm/nodelibs-vm@0.1.0"
    },
    "npm:assert@1.3.0": {
      "util": "npm:util@0.10.3"
    },
    "npm:browserify-aes@1.0.5": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "buffer-xor": "npm:buffer-xor@1.0.3",
      "cipher-base": "npm:cipher-base@1.0.1",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:browserify-cipher@1.0.0": {
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "browserify-des": "npm:browserify-des@1.0.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0"
    },
    "npm:browserify-des@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "des.js": "npm:des.js@1.0.0",
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:browserify-rsa@2.0.1": {
      "bn.js": "npm:bn.js@2.2.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "constants": "github:jspm/nodelibs-constants@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:browserify-sign@3.0.8": {
      "bn.js": "npm:bn.js@2.2.0",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.1.0",
      "inherits": "npm:inherits@2.0.1",
      "parse-asn1": "npm:parse-asn1@3.0.2",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:buffer-xor@1.0.3": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:buffer@3.5.1": {
      "base64-js": "npm:base64-js@0.0.8",
      "ieee754": "npm:ieee754@1.1.6",
      "is-array": "npm:is-array@1.0.1"
    },
    "npm:cipher-base@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0",
      "string_decoder": "github:jspm/nodelibs-string_decoder@0.1.0"
    },
    "npm:constants-browserify@0.0.1": {
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:core-util-is@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:create-ecdh@2.0.2": {
      "bn.js": "npm:bn.js@2.2.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "elliptic": "npm:elliptic@3.1.0"
    },
    "npm:create-hash@1.1.2": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "cipher-base": "npm:cipher-base@1.0.1",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "ripemd160": "npm:ripemd160@1.0.1",
      "sha.js": "npm:sha.js@2.4.4"
    },
    "npm:create-hmac@1.1.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "stream": "github:jspm/nodelibs-stream@0.1.0"
    },
    "npm:crypto-browserify@3.10.0": {
      "browserify-cipher": "npm:browserify-cipher@1.0.0",
      "browserify-sign": "npm:browserify-sign@3.0.8",
      "create-ecdh": "npm:create-ecdh@2.0.2",
      "create-hash": "npm:create-hash@1.1.2",
      "create-hmac": "npm:create-hmac@1.1.4",
      "diffie-hellman": "npm:diffie-hellman@3.0.2",
      "inherits": "npm:inherits@2.0.1",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "public-encrypt": "npm:public-encrypt@2.0.1",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:des.js@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "inherits": "npm:inherits@2.0.1",
      "minimalistic-assert": "npm:minimalistic-assert@1.0.0"
    },
    "npm:diffie-hellman@3.0.2": {
      "bn.js": "npm:bn.js@2.2.0",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "miller-rabin": "npm:miller-rabin@2.0.1",
      "randombytes": "npm:randombytes@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:elliptic@3.1.0": {
      "bn.js": "npm:bn.js@2.2.0",
      "brorand": "npm:brorand@1.0.5",
      "hash.js": "npm:hash.js@1.0.3",
      "inherits": "npm:inherits@2.0.1",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:es6-promise@3.0.2": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:evp_bytestokey@1.0.0": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0"
    },
    "npm:hash.js@1.0.3": {
      "inherits": "npm:inherits@2.0.1"
    },
    "npm:inherits@2.0.1": {
      "util": "github:jspm/nodelibs-util@0.1.0"
    },
    "npm:miller-rabin@2.0.1": {
      "bn.js": "npm:bn.js@2.2.0",
      "brorand": "npm:brorand@1.0.5"
    },
    "npm:parse-asn1@3.0.2": {
      "asn1.js": "npm:asn1.js@2.2.1",
      "browserify-aes": "npm:browserify-aes@1.0.5",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "evp_bytestokey": "npm:evp_bytestokey@1.0.0",
      "pbkdf2": "npm:pbkdf2@3.0.4",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:path-browserify@0.0.0": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:pbkdf2@3.0.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "child_process": "github:jspm/nodelibs-child_process@0.1.0",
      "create-hmac": "npm:create-hmac@1.1.4",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "path": "github:jspm/nodelibs-path@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "systemjs-json": "github:systemjs/plugin-json@0.1.0"
    },
    "npm:process@0.11.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0"
    },
    "npm:public-encrypt@2.0.1": {
      "bn.js": "npm:bn.js@2.2.0",
      "browserify-rsa": "npm:browserify-rsa@2.0.1",
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "create-hash": "npm:create-hash@1.1.2",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "parse-asn1": "npm:parse-asn1@3.0.2",
      "randombytes": "npm:randombytes@2.0.1"
    },
    "npm:randombytes@2.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "crypto": "github:jspm/nodelibs-crypto@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:readable-stream@1.1.13": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "core-util-is": "npm:core-util-is@1.0.1",
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "isarray": "npm:isarray@0.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2",
      "stream-browserify": "npm:stream-browserify@1.0.0",
      "string_decoder": "npm:string_decoder@0.10.31"
    },
    "npm:reflect-metadata@0.1.2": {
      "assert": "github:jspm/nodelibs-assert@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:ripemd160@1.0.1": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:rx@2.5.1": {
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:sha.js@2.4.4": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0",
      "fs": "github:jspm/nodelibs-fs@0.1.2",
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:stream-browserify@1.0.0": {
      "events": "github:jspm/nodelibs-events@0.1.1",
      "inherits": "npm:inherits@2.0.1",
      "readable-stream": "npm:readable-stream@1.1.13"
    },
    "npm:string_decoder@0.10.31": {
      "buffer": "github:jspm/nodelibs-buffer@0.1.0"
    },
    "npm:util@0.10.3": {
      "inherits": "npm:inherits@2.0.1",
      "process": "github:jspm/nodelibs-process@0.1.2"
    },
    "npm:vm-browserify@0.0.4": {
      "indexof": "npm:indexof@0.0.1"
    },
    "npm:zone.js@0.5.8": {
      "es6-promise": "npm:es6-promise@3.0.2",
      "process": "github:jspm/nodelibs-process@0.1.2"
    }
  }
});
